### ISSUE TITLE
22.9/3 LC 53 - I. 在排序数组中查找数字 I.cpp

### ISSUE THREAD

**Issue by TangentOne** [TangentOne/40Everyday#4]
@Vinter8848 

代码仅执行了一次二分，算法时间复杂度仍为O(N),可以尝试使用二分查找法进行优化，将时间复杂度降为O(logN)
[参考链接](https://blog.csdn.net/Master_cxc/article/details/91415170)

**Comment by Vinter8848** [comment]
#include<iostream>
#include<vector>
using namespace std; 
class Solution {
public:
    int search(vector<int>& nums, int target)
    {
        int top = 0;
        int end = nums.size()-1;
        int count = 0;
        if (end < 0)
            return 0;
        if (nums[top] > target || nums[end] < target)
            return 0;
        int mid = (top+end) / 2;
        while (nums[mid]<target)
        {
            if (top != end)
            {
                top = mid+1;
            }
            mid = (top + end) / 2;
            if (top == end && top == mid)
                break;
            
        }
        while (nums[mid]>target)
        {
            if (top != end)
            {
                end = mid-1;
            }
            mid=(top + end) / 2;
            if (top == end && top == mid)
                break;
            
        }
      
    for (int i = top; i <= end; i++)
    {
        if (nums[i] == target)
            count++;
    }
    return count;
     
        
    }
};
int main()
{
    Solution tool;
    vector<int>num = {0,1,2,3,4,4,4};

    cout << tool.search(num,2);
}
