### ISSUE TITLE
22.9/3/跳台阶.cpp

### ISSUE THREAD

**Issue by TangentOne** [TangentOne/40Everyday#5]
@JacksonChanp @SherrySquirrel 
在递归的过程中，有些值可能**被多次计算**，造成时间资源的浪费。
例如，在计算**jump(6)**时，先要计算**jump(5)**和**jump(4)**，而在计算**jump(5)**时会计算**jump(4)**和**jump(3)**.
这样，**jump(4)**就会被**两次计算**，同理，**jump(3)**会被**计算四次**......

试着记录jump(x)的值，当jump(x)第一次被求值时，正常求值，并记录。当jump(x)被第二次求值时，直接返回记录的值。

除此之外，容易推出jump的值满足
> jump[n]=jump[n-1]+jump[n-2]

而jump[0]=jump[1]=1，那么jump[2]=jump[0]+jump[1]=2......通过这种方法先预处理出jump[0...15]的值，直接返回对应的值即可

**Comment by JacksonChanp** [comment]
拿数组存储可以吗

**Comment by TangentOne** [comment]
可以，就是这个意思😘
